#include<stdio.h>
#include<sys/socket.h>
#include<stdlib.h>
#include<errno.h>
#include<unistd.h>
#include<signal.h>
#include<time.h>
#include<netdb.h>
#include<string.h>
#include<arpa/inet.h>
#include<memory.h>
